services:
  mcp-tools-fetch:
    build:
      context: .
    container_name: mcp-tools-fetch
    ports:
      - "8383:8383"
    working_dir: /app
    restart: always
    stdin_open: true
    tty: true
    #command: "/bin/sh"
    command: "--pass-environment --sse-port=8383 --sse-host 0.0.0.0 uv run mcp-server-fetch"